// Regenerates src/styles/fonts.inlined.ts with base64-embedded woff2 subsets
// for Poppins (500/600/700) and Lora (400/500). Run via `pnpm build:fonts`.
//
// Requires outbound network + the `subset-font` devDep. If either is missing,
// the stub committed at src/styles/fonts.inlined.ts will be used instead.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import subsetFont from "subset-font";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "../src/styles");

const FONTS = [
  {
    family: "Poppins",
    weights: [500, 600, 700],
    urlFor: (w) =>
      `https://github.com/google/fonts/raw/main/ofl/poppins/Poppins-${
        w === 500 ? "Medium" : w === 600 ? "SemiBold" : "Bold"
      }.ttf`,
  },
  {
    family: "Lora",
    weights: [400, 500],
    urlFor: (w) =>
      `https://github.com/google/fonts/raw/main/ofl/lora/static/Lora-${
        w === 400 ? "Regular" : "Medium"
      }.ttf`,
  },
];

const LATIN_RANGES =
  "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD";

const SUBSET_CHARS =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,;:!?@#$%&*()-+=/\"'";

async function fetchBuffer(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`fetch ${url} failed: ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

function faceRule(family, weight, b64) {
  return `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:swap;src:url('data:font/woff2;base64,${b64}') format('woff2');unicode-range:${LATIN_RANGES};}`;
}

function writeStub() {
  // Must stay byte-identical to the committed stub so `git status` is clean
  // when the network fetch or subsetter fails.
  const ts = `// Generated by scripts/build-fonts.mjs — placeholder (will be regenerated in CI).\nexport const inlinedFonts = "";\n`;
  writeFileSync(resolve(outDir, "fonts.inlined.ts"), ts);
}

async function main() {
  try {
    const parts = [];
    for (const f of FONTS) {
      for (const w of f.weights) {
        const src = f.urlFor(w);
        const buf = await fetchBuffer(src);
        const woff2 = await subsetFont(buf, SUBSET_CHARS, {
          targetFormat: "woff2",
        });
        parts.push(faceRule(f.family, w, woff2.toString("base64")));
      }
    }
    const ts = `// Generated by scripts/build-fonts.mjs — do not edit by hand.\nexport const inlinedFonts = ${JSON.stringify(parts.join(""))};\n`;
    writeFileSync(resolve(outDir, "fonts.inlined.ts"), ts);
    console.log(`wrote ${parts.length} @font-face rules`);
  } catch (err) {
    console.warn(
      `[build-fonts] falling back to stub: ${err && err.message ? err.message : err}`,
    );
    writeStub();
  }
}

main();
