import type { WrappedBlob } from "./crypto.js";

const DB_NAME = "stawi-auth-v1";
const STORE = "sessions";

export interface Session {
  wrapKey?: CryptoKey;
  dpopKey?: CryptoKeyPair;
  wrappedRT: WrappedBlob;
  lastIdToken?: string;
  updatedAt: number;
}

// Only the serializable parts are persisted to IDB
type PersistedShape = { wrappedRT: WrappedBlob; lastIdToken?: string; updatedAt?: number };

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => req.result.createObjectStore(STORE);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function tx(db: IDBDatabase, mode: IDBTransactionMode): IDBObjectStore {
  return db.transaction(STORE, mode).objectStore(STORE);
}

function isValid(v: unknown): v is PersistedShape {
  if (!v || typeof v !== "object") return false;
  const o = v as any;
  // Check if wrappedRT exists and has iv/ciphertext - indexedDB may change their types
  if (!o.wrappedRT || typeof o.wrappedRT !== "object") return false;
  const iv = o.wrappedRT.iv;
  const ct = o.wrappedRT.ciphertext;
  // Both should be array-like with byteLength (covers Uint8Array and plain arrays from IDB)
  return (iv && (iv instanceof Uint8Array || (iv instanceof Array) || iv.byteLength !== undefined))
    && (ct && (ct instanceof Uint8Array || (ct instanceof Array) || ct.byteLength !== undefined));
}

export async function loadSession(namespace: string): Promise<Session | null> {
  const db = await openDb();
  try {
    return await new Promise<Session | null>((resolve) => {
      const req = tx(db, "readonly").get(namespace);
      req.onsuccess = () => {
        const v = req.result;
        if (!isValid(v)) return resolve(null);
        // Keys are not persisted; they must be regenerated by caller
        // Ensure iv/ciphertext are Uint8Array (IDB may have stored them differently)
        const result = {
          wrappedRT: {
            iv: new Uint8Array(v.wrappedRT.iv),
            ciphertext: new Uint8Array(v.wrappedRT.ciphertext),
          },
          lastIdToken: v.lastIdToken,
          updatedAt: v.updatedAt ?? 0,
        };
        resolve(result);
      };
      req.onerror = () => resolve(null);
    });
  } finally { db.close(); }
}

export async function saveSession(namespace: string, s: Omit<Session, "updatedAt">): Promise<void> {
  const db = await openDb();
  try {
    // Only persist serializable data; keys are not stored
    const persisted: PersistedShape = {
      wrappedRT: s.wrappedRT,
      lastIdToken: s.lastIdToken,
      updatedAt: Date.now(),
    };
    await new Promise<void>((resolve, reject) => {
      const req = tx(db, "readwrite").put(persisted, namespace);
      req.onsuccess = () => resolve();
      req.onerror = () => reject(req.error);
    });
  } finally { db.close(); }
}

export async function clearSession(namespace: string): Promise<void> {
  const db = await openDb();
  try {
    await new Promise<void>((resolve, reject) => {
      const req = tx(db, "readwrite").delete(namespace);
      req.onsuccess = () => resolve();
      req.onerror = () => reject(req.error);
    });
  } finally { db.close(); }
}
